pipeline {
    agent any
    parameters {
        string( defaultValue: 'hello-world', description: "Project Name", name: 'PROJECT_NAME')
        string( defaultValue: 'us-west-2', description: "Deployment Region", name: 'DEPLOYMENT_REGION')
    }
    stages {
        stage ('Initialize') {
            steps {
                sh "rm -rf eks_test"
                sh "git clone git@github.com:mohil194250/eks_test.git"
            }
        }
        stage ('build') {
            steps {
                sh "sudo docker build -t humancloudak/k8-poc ."
                sh "sudo docker push humancloudak/k8-poc"
            }
        }
        stage ('deploy to dev') {
            steps {
                sh "helm upgrade --install eks-test-dev --set image.repository=humancloudak/k8-poc --set image.tag=latest --set image.pullPolicy=Always bitnami/tomcat -n dev"
            }
        }

        stage ('deploy to uat') {
            steps {
                sh "helm upgrade --install eks-test-uat --set image.repository=humancloudak/k8-poc --set image.tag=latest --set image.pullPolicy=Always bitnami/tomcat -n uat"
            }
        }
        stage ('deploy to prod') {
            steps {
                sh "helm upgrade --install eks-test-prod --set image.repository=humancloudak/k8-poc --set image.tag=latest --set image.pullPolicy=Always bitnami/tomcat -n prod"
            }
        }
        
    }
}
    
    