pipeline {
    agent any
    parameters {
        choice( choices: ['dev', 'uat' ,'prod'], description: "Deployment Environment", name: 'ENVIRONMENT_TYPE')
        string( defaultValue: 'hello-world', description: "Project Name", name: 'PROJECT_NAME')
        // string( defaultValue: 'dev', description: "Deployment Environment", name: 'ENVIRONMENT_TYPE')
         string( defaultValue: 'us-west-2', description: "Deployment Region", name: 'DEPLOYMENT_REGION')
        // booleanParam ( defaultValue: 'false', description: "Run Terraform Plan Only", name: 'DRY_RUN')
    }
    stages {
        stage ('Initialize') {
            steps {
                sh "rm -rf eks_test"
                sh "git clone git@github.com:mohil194250/eks_test.git"
            }
        }
        stage ('build') {
            steps {
                sh "sudo docker build -t humancloudak/k8-poc ."
                sh "sudo docker push humancloudak/k8-poc"
            }
        }

        stage ('deploy') {
            steps {
                sh "kubectl delete -f deployment.yaml"
                sh "aws eks update-kubeconfig --name eks-test-cluster --region us-west-2"
                sh "kubectl create -f deployment.yaml"
                sh "kubectl get pods"
            }
        }

        stage ('dev to uat') {
            steps {
                sh " "
            }
        }

        stage ('uat to dev') {
            steps {
                sh ""
            }
        }

        
    }
}
    
    